### ISSUE TITLE
[feature] file params

### ISSUE THREAD

**Issue by Dafaque** [claceio/clace#44]
Implement file picking and processing for Action Apps.
Picking: 
 - sutable UI
 - sending to backend as multipart or stream

Processing:
- param type ace.FILE (underlying stream, filename, and it's len i guess)
- some fs funcs to be able discover, store and read files
- make `ace.result()` to be able to accept new type, which causes download
- make `http.in.post` to be able handle new type into mulipart or stream request

For me use case is to create wrappers around some AI cmd's which has no REST.
I want to: 
- get file from form
- store it
- pass it's location into cmd
- await for result
- get result file and respond it back to user

**Comment by akclace** [comment]
Thanks for filing the ticket. I am taking a look at what changes are required for adding file upload/download support for Actions

**Comment by akclace** [comment]
Added display_type support in param definition, see https://github.com/claceio/clace/blob/fa8a97c5ab6435ee4edbdca14039156f9fd105c6/internal/app/tests/appaction_test.go#L867

For string types, display_type can be FILE/PASSWORD/TEXTAREA. For file, the file is uploaded and saved to a temp directory on the server. args.param_name will reference the temp file name on disk. It can be passed to exec.run to process the file data.

Multiple file type params are supported, each param supports single file upload only. The temp directory is deleted at the end of the action handler function.

Returning output file requires more work. If the run command generates a file on disk, referencing that file name directly will not work when multiple Clace servers are present behind a load balancer (since file will be on one of the machines). The plan is to add a fs.load_file API which will load file from disk to the Clace managed database. The ace.result will return a reference to that uploaded file, so that the API access will work from any machine.

**Comment by akclace** [comment]
Pushed release 0.9.8 with updates. https://github.com/claceio/apps/tree/main/misc/num_lines is a sample app which shows file upload and download. `exec` takes a new `stdout_file` option which causes the output to be written to a temp file. `fs.load_file` creates a db entry specifying the metadata for the file to be served. ace.result accepts a report type of `ace.DOWNLOAD` or `ace.IMAGE` (for image display). The temp file created by exec is deleted after the first download is done (or 60 minutes after the load_file call). Doc updates are pending.

@Dafaque let me know any feedback. exec workflow should work, more work is required for http plugin file post support

**Comment by Dafaque** [comment]
Give me please time untill this Sat, I'll check out if this fit my requirements. Thank you very much for speed!

**Comment by akclace** [comment]
No problem, take your time
